import Link from 'next/link';
import React from 'react';
import styles from './Header.module.scss';
import { useRouter } from 'next/router';
import Head from 'next/head';

const Header: React.FC = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Portfolio Rafi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <ul>
          <li className={router.pathname == '/' ? styles.active : ''}>
            <Link href="/">Muhammad Rafiudin</Link>
          </li>
          <li className={router.pathname == '/projects' ? styles.active : ''}>
            <Link href="/projects">Projects</Link>
          </li>
          <li className={router.pathname == '/blogs' ? styles.active : ''}>
            <Link href="/blogs">Blogs</Link>
          </li>
          <li className={router.pathname == '/chat' ? styles.active : ''}>
            <Link href="/chat">Chat with me</Link>
          </li>
        </ul>
      </header>
    </>
  );
};

export default Header;
